backend:
  name: test-repo
media_folder: static/img
public_folder: /img/uploads
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Home title", name: title, widget: string}
      - file: "/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Contact title", name: "title", widget: "string"}
